### ISSUE TITLE
Add a checklist at the time of talk submission

### ISSUE THREAD

**Issue by tathagata** [chicagopython/chipy.org#111]
Having checklist/guideline shown at the time of talk submission (http://www.chipy.org/meetings/topics/propose) will help the speaker prepare a better talk:

What to *avoid*:
- Too much code with context 
- If its a technical talk, no code 

What to be mindful of:
-  Proprietary code with no relevant open source references

Please suggest What else should be included:
- Pycon advise (https://us.pycon.org/2014/speaking/proposal_advice/)

**Comment by JoeJasinski** [comment]
Good idea.  I think it would be help to have a description on that apge.

**Comment by JoeJasinski** [comment]
@tathagata and @brianray.  I've added a flatblock speaker_text and sponsor_info_text on the submit a talk and sponsor list page respectively.  This allows a user to customize the text via the Flatblocks editor in the Django admin.  

However, I made this change to the feature/django18 branch so deploying this will depend on the pull request https://github.com/chicagopython/chipy.org/pull/108 (which is basically ready to go, but I could some eyes on it to test before pushing out this major update)

**Comment by JoeJasinski** [comment]
@tathagata and @brianray: With the recent deployment of the 1.8 changes, these text fields are now available to add text to the Sponsor and Meeting Proposal pages pages.

Sponsors front end
http://www.chipy.org/sponsors/list/
Sponsors backe end
http://www.chipy.org/admin/flatblocks/flatblock/2/

Propose topic front end
http://www.chipy.org/meetings/topics/propose/
Propose topic back end.
http://www.chipy.org/admin/flatblocks/flatblock/3/

If this looks good to you, I think you can close this issue.

**Comment by tathagata** [comment]
Awesome! I made the change so that the following text appears before the talk proposal form

![image](https://cloud.githubusercontent.com/assets/68151/13242891/24b89eb8-d9bf-11e5-93ab-83a61fc01b8f.png)

Thanks @JoeJasinski!

**Comment by JoeJasinski** [comment]
Nice
