### ISSUE TITLE
"Platinum Sponsor" section doesn't show up on http://www.chipy.org/ when no meeting is set

### ISSUE THREAD

**Issue by agfor** [chicagopython/chipy.org#112]
I noticed it this morning before next month's meeting was added.

**Comment by agfor** [comment]
@JoeJasinski ping. This is currently a problem as I can't show potential sponsors what the logos on the site look like.

**Comment by JoeJasinski** [comment]
@agfor  For the time being, creating a new meeting solves the issue.  I've done that on the site for January.  

Note: I've been avoiding doing too much more work on the site until the Django 1.8 changes are deployed to avoid having to support two different development environments.  I can roll in this change with the Django 1.8 pull request.

**Comment by agfor** [comment]
Thanks, that solves the problem for now!

**Comment by JoeJasinski** [comment]
Pull request to fix this:

https://github.com/chicagopython/chipy.org/pull/120

**Comment by JoeJasinski** [comment]
This should be fixed.  I'm going to close this for now, unless anyone sees a reason to keep it open.

**Comment by agfor** [comment]
Thanks @JoeJasinski!
