### ISSUE TITLE
Sync failed with meetup.com

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#113]
<img width="1007" alt="screen shot 2015-12-07 at 1 11 00 am" src="https://cloud.githubusercontent.com/assets/676284/11620310/7ef7e172-9c7f-11e5-86c5-c4421e17ce0d.png">

**Comment by emperorcezar** [comment]
Pushed a fix. Try again.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by brianray** [comment]
:+1:
