### ISSUE TITLE
Add a Jekyll blog

### ISSUE THREAD

**Issue by tanyaschlusser** [chicagopython/chipy.org#116]
Add a place to blog that's simple and static. The goal is to have pages featuring
- The mentor/mentee pairs in each future cohort
- 'Python Shop of the Month' or maybe 'Hosts' blog posts where we highlight our hosts
- 'Pythonista of the Month' posts to encourage people to meet each other
- Summary stats from prior ChiPy member surveys
- Maybe one other thing, like featuring one of our SIGs or something else local

I'll copy ChiPy CSS styles and follow the [GitHub Jekyll instructions](https://help.github.com/articles/using-jekyll-with-pages/). The goal will be to make it simple enough that novice mentees can add posts and thus be introduced to GitHub.

**Comment by tanyaschlusser** [comment]
The blog should be in a separate repo, not this one, called **chicagopython.github.io** -- [here is a draft][draft-blog]. The [repo is here, temporarily][draft-blog-repo]. I'll email the group about it too.

[draft-blog]: http://tanyaschlusser.github.io/tmp
[draft-blog-repo]: https://github.com/tanyaschlusser/tmp

**Comment by emperorcezar** [comment]
Created the blog repo and added you as a collaborator. Go for it.

**Comment by tanyaschlusser** [comment]
Yay! Thank you Cezar!
Would it be possible to rename it to **chicagopython.github.io**?  (It [has to have that name in order to work][gh-pages].)

[gh-pages]: https://pages.github.com/

**Comment by emperorcezar** [comment]
Done.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by tanyaschlusser** [comment]
Thank you!

**Comment by emperorcezar** [comment]
@tanyaschlusser Is there anything else you need for this?

**Comment by tanyaschlusser** [comment]
No -- although maybe I'll try Lektor (a new Python project) instead of Jekyll...
still intend to do this :-)  sorry for the delay.

**Comment by elmq0022** [comment]
@raymondberg @smandekar1 
Looks like this is up and runnings.  Any  issues with closing this issue.  My only thought is adding a link to the blog from chipy.org.

**Comment by smandekar1** [comment]
can be closed, probably don't need to link to it.
