### ISSUE TITLE
Add talk level to propose

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#118]
Add level to Propose Talk:
- [ ] novice
- [ ] intermediate 
- [ ] advanced

**Comment by JoeJasinski** [comment]
Hey all, I've added this functionality.  I've made this a required field on the talk submission page. I'll submit a pull request shortly.

**Comment by JoeJasinski** [comment]
I've created a pull request for this:

https://github.com/chicagopython/chipy.org/pull/119

**Comment by JoeJasinski** [comment]
This is done.  Closing
