### ISSUE TITLE
Make Platinum Sponsor logos on homepage larger

### ISSUE THREAD

**Issue by agfor** [chicagopython/chipy.org#121]
The logos are pretty small, I think we should let them take up the whole column width.

Currently, we're [displaying thumbnails](https://github.com/chicagopython/chipy.org/blob/master/chipy_org/templates/homepage.html#L133):

    {% thumbnail general_sponsor.sponsor.logo "150" crop="center" as im %}

I think displaying the original logos should work without any other changes to the template. I haven't tested this in code, but when I manually edit the DOM it looks correct.

Prereq: change the [ordering from lexicographic to random](https://github.com/chicagopython/chipy.org/pull/120#issuecomment-187567474) so no logo is disproportionately pushed off the bottom of the screen.

**Comment by JoeJasinski** [comment]
@agfor can you tell me the DOM manipulations you are making so I can try to reproduce?  I think we'll still want to generate thumbnails - even if we make them large enough to fit the the entire column - to avoid large downloads.

**Comment by JoeJasinski** [comment]
Actually, setting the image width %100 might work...

**Comment by agfor** [comment]
I replaced the `src` attribute of each image with the original URL of the images from the individual sponsor pages. The images filled the column and no other page layout appeared to change.

It looks like those are [actually thumbnails as well, just larger ones](https://github.com/chicagopython/chipy.org/blob/master/chipy_org/apps/sponsors/templates/sponsors/sponsor_detail.html#L15) -- so it might be as simple as changing the width from 150 to 400 in the thumbnail tag.

**Comment by JoeJasinski** [comment]
Setting the site to 400 looks to work.  I've added it to the pull request for https://github.com/chicagopython/chipy.org/pull/120

**Comment by JoeJasinski** [comment]
This has been deployed.

**Comment by JoeJasinski** [comment]
I'm going to close this unless anyone objects.
