### ISSUE TITLE
Add contributors

### ISSUE THREAD

**Issue by agfor** [chicagopython/chipy.org#122]
@emperorcezar Please add the other ChiPy organizers as contributors.

Most importantly @JoeJasinski, but @tathagata, @tanyaschlusser (if she's still interested), @jerry-dumblauskas, and me -- those are the users who's names are auto-completing who are also organizers, I don't know if the others are interested.

At the very least, I could close some of the old issues that have been resolved.

**Comment by emperorcezar** [comment]
Have a new team and all have access. You should find your invites.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by jerry-dumblauskas** [comment]
yhx
