### ISSUE TITLE
Unable to change RSVP to no.

### ISSUE THREAD

**Issue by hectron** [chicagopython/chipy.org#125]
When a user was trying to change an RSVP to no, the website threw an error. It can be seen in the screenshot.

Submitted through e-mail.

![unnamed](https://cloud.githubusercontent.com/assets/1649281/13653533/e0f18d74-e617-11e5-9297-af4c9fb058fc.png)

**Comment by JoeJasinski** [comment]
I tried to reproduce and was successfully able to submit a "no" rsvp. @emperorcezar did you happen to get any error emails recently?

**Comment by emperorcezar** [comment]
All fixed now.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.
