### ISSUE TITLE
captcha not showing on rsvp form when logging in anonymously

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#126]
Hey all, 

Someone just reported that the captcha was not displaying on the Anonymous RSVP form, which is preventing the form submission.  The captcha does appear to be working on the contact form.  

I was able to replicate by opening a new private browser tab and submitting an rsvp anonymously.  The result is a missing captcha form validation error.

**Comment by emperorcezar** [comment]
Pushing fix now

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.
