### ISSUE TITLE
Email organizers when a topic is proposed

### ISSUE THREAD

**Issue by agfor** [chicagopython/chipy.org#128]
When a new topic object (http://www.chipy.org/admin/meetings/topic/) is created using the "Give a talk" form (http://www.chipy.org/meetings/topics/propose/) the details should be emailed to chicago-organizers@python.org

**Comment by JoeJasinski** [comment]
I've got this working locally, but would still like to do more testing...

https://github.com/JoeJasinski/chipy.org/tree/feature/email_topic_submit

**Comment by JoeJasinski** [comment]
Added a new pull request to address this:

https://github.com/chicagopython/chipy.org/pull/130

**Comment by JoeJasinski** [comment]
This has been deployed.

**Comment by agfor** [comment]
Great! Thanks for taking care of this.
