### ISSUE TITLE
Chipy.org LICENSE file references wrong project

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#131]
Though we were using Pinax for the first iteration of this site, I don't think any bit of it is used here. 

```
Symposium code is:

Copyright (c) 2000-2012 Eldarion, Inc and contributors.
```

**Comment by JoeJasinski** [comment]
https://github.com/chicagopython/chipy.org/blob/master/LICENSE#L1

**Comment by emperorcezar** [comment]
Don't know if there is any of that code left. You'll notice the second part of the license is for the chipy site and refers to it as such.

**Comment by elmq0022** [comment]
We show an MIT licence.  Closing.
