### ISSUE TITLE
ChiPy Homepage Refresh

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#136]
I'd like to propose refreshing the design of the homepage to modernize it a bit.
- make it more mobile friendly by making it responsive
- creating a modern long-scrolling sectional page layout 
  - could add parallax for some pizazz :-)
- Integrate sections for:
  - upcoming meeting schedule (should also accommodate SIG announcements)
    - easy to see calendar of upcoming events
    - somehow integrate upcoming topics
  - easy to attend a meeting 
    - registration workflow (mobile friendly)
  - sponsor list
  - blog or announcement app for posting meeting announcements and general news
  - possibly social feeds / pictures of meetings / etc. 
  - links to external resources easily available (meetup / twitter / github / etc)
  - links to common tasks that are easily discoverable 
    - link to contact us 
    - link to add to mailing list
    - link to donate 
    - link to give talk
    - link to host a venue
    - link to more info about SIG 
  - more?

Here is a rough mockup: 
[ChiPy Homepage Mockup.pdf](https://github.com/chicagopython/chipy.org/files/356396/ChiPy.Homepage.Mockup.pdf)

Example layouts:
- http://startbootstrap.com/template-categories/one-page/

Chi Hack Night has a good example:
- https://chihacknight.org/

**Comment by brianray** [comment]
I see you put some good thought into this. It would be nice to hear what others thing.

**Comment by jerry-dumblauskas** [comment]
looks great.  Can we add an easily discoverable button for the referral
program as well?

**Comment by emperorcezar** [comment]
I like the mockup a lot. With a little logic to hide some areas when empty
it will be really great. Is someone good at the the html/css wrangling? I
can do it, but I'd be slower than some others.

-------------------------------------------------------------------------------------------------------------
Father, Pythonista, Cyclist, Brewer. Dabbling in Clojure and Functional
Languages

**Comment by JoeJasinski** [comment]
@jerry-dumblauskas I like the referral button idea. 

@emperorcezar I'm in the same boat regarding html/css, but I don't mind poking around with it.

**Comment by brianray** [comment]
It would probably help to get a UI/UX person involved. Please note our
original design was done at Imaginary Landscape

**Comment by JoeJasinski** [comment]
Here is a proposal Rough Draft.  Message me if you want edit access.

https://docs.google.com/document/d/1u9O0sJEcOfuV8gdCtN7ROPtIbhtY_90fjNhlhlHcDtg/edit#heading=h.idcmi8g4cdbo

**Comment by JoeJasinski** [comment]
I've started doing some prototyping on the backend (and some basic frontend work) need to support this.  Specifically, I've added models and sections on the homepage for non-main ChiPy meetings (eg SIG meetings).  

Work in progress: 
https://github.com/JoeJasinski/chipy.org/tree/feature/other-meetings

**Comment by brianray** [comment]
@adeolapure

**Comment by JoeJasinski** [comment]
@here 

I've made progress on the ChiPy re-design. I haven't touched the re-skin bit, but I've added much of the functionality for SIG support. I'll make a list of in-depth changes in a future post, but for now, here's the dev site for viewing. 

http://chipy-dev.herokuapp.com/

**Comment by adeolapure** [comment]
@JoeJasinski Sweeet! I actually just added the ChiPy twitter feed to the homepage (pending pull request merge)

I designed it according to the current design. I do have thoughts on the new Participants section if you're open to them!

**Comment by emperorcezar** [comment]
@JoeJasinski I'm liking it. What else is there to be done with it?

**Comment by JoeJasinski** [comment]
@adeolapure I'm glad for any feedback on the participate section. 

@emperorcezar I think it's wrapping up, though this is intended to be just a first pass.  The SIG detail pages are pretty sparse at the moment, but perhaps we can build those out as we find how how they might be sued.

**Comment by JoeJasinski** [comment]
Pull request: 
https://github.com/chicagopython/chipy.org/pull/151
