### ISSUE TITLE
Tests failing due to django-social-auth

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#139]
Hey all,

This weekend, I was doing some standard Python updates and maint in a local branch hoping to bring us closer to a python3.x transition.  

https://github.com/JoeJasinski/chipy.org/tree/feature/cleanup-and-updates-2

In this branch, I've made the following changes:
- updates to a bunch of the python requirements 
- changes to the auth.User import and relationships involving auth.User to support Django 1.6+ style of referencing the django auth user 
- added a bunch of very basic unit tests to help us determine broken urls 
- move to python-social-auth

However, during this process, I realized that Django-Social-Auth is causing the tests to fail.  Django-social-auth is an abandoned project and the authors recommend using python-social-auth instead (basically a project rebrand). In fact, I don't think Django-social-auth even supports Django 1.6+, but it seems to be working currently on our site. 

I spent some time this weekend trying to move to python-social-auth (which does support Python 3). However, the this upgrade requires a database state change for which there is no migration for.  (The initial migration in python-social-auth does not match our current database state)  Therefore, the ./manage.py migrate command does not apply properly even when faking the first migration. 

Wondering if anyone has any ideas how to make this transition without losing the associations between our Users and their social accounts.

**Comment by emperorcezar** [comment]
Can you elaborate on the db changes needed? When I moved to PSA in other projects I didn't have many issues. Is it possible that the DSA version is too old and that will need to be upgraded first?

**Comment by imagescape** [comment]
The DSA version is actually the most recent released version 0.7.28.  The models in DSA actually point to PSA. 

Our models (in the DDL below), do not match the initial migration for python-social-auth. 

https://github.com/omab/python-social-auth/blob/master/social/apps/django_app/default/migrations/0001_initial.py#L30

There is a table called Code that doesn't exist in our database.  Maybe we just need to create that table manually.  At first, I thought the differences were much more drastic, but on closer look, the other tables look pretty similar on a field-by-field basis.  

```
chipy_org=# \d social_auth_association
                                   Table "public.social_auth_association"
   Column   |          Type          |                              Modifiers                               
------------+------------------------+----------------------------------------------------------------------
 id         | integer                | not null default nextval('social_auth_association_id_seq'::regclass)
 server_url | character varying(255) | not null
 handle     | character varying(255) | not null
 secret     | character varying(255) | not null
 issued     | integer                | not null
 lifetime   | integer                | not null
 assoc_type | character varying(64)  | not null
Indexes:
    "social_auth_association_pkey" PRIMARY KEY, btree (id)


chipy_org=# \d social_auth_nonce;
                                   Table "public.social_auth_nonce"
   Column   |          Type          |                           Modifiers                            
------------+------------------------+----------------------------------------------------------------
 id         | integer                | not null default nextval('social_auth_nonce_id_seq'::regclass)
 server_url | character varying(255) | not null
 timestamp  | integer                | not null
 salt       | character varying(40)  | not null
Indexes:
    "social_auth_nonce_pkey" PRIMARY KEY, btree (id)


chipy_org=# \d social_auth_usersocialauth;
                                   Table "public.social_auth_usersocialauth"
   Column   |          Type          |                                Modifiers                                
------------+------------------------+-------------------------------------------------------------------------
 id         | integer                | not null default nextval('social_auth_usersocialauth_id_seq'::regclass)
 user_id    | integer                | not null
 provider   | character varying(32)  | not null
 uid        | character varying(255) | not null
 extra_data | text                   | not null
Indexes:
    "social_auth_usersocialauth_pkey" PRIMARY KEY, btree (id)
    "social_auth_usersocialauth_provider_uid_key" UNIQUE CONSTRAINT, btree (provider, uid)
    "social_auth_usersocialauth_user_id" btree (user_id)
Foreign-key constraints:
    "social_auth_usersocial_user_id_193b2d80880502b2_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED


chipy_org=# \d social_auth_usersocialauth_user_id 
Index "public.social_auth_usersocialauth_user_id"
 Column  |  Type   | Definition 
---------+---------+------------
 user_id | integer | user_id
btree, for table "public.social_auth_usersocialauth"
```

**Comment by JoeJasinski** [comment]
Update: meant to post as this user.

The DSA version is the most recent released version 0.7.28.  The models in DSA actually point to PSA. 

Our models (in the DDL below), do not match the initial migration for python-social-auth. 

https://github.com/omab/python-social-auth/blob/master/social/apps/django_app/default/migrations/0001_initial.py#L30

There is a table called Code that doesn't exist in our database.  Maybe we just need to create that table manually.  At first, I thought the differences were much more drastic, but on closer look, the other tables look pretty similar on a field-by-field basis.  

```
chipy_org=# \d social_auth_association
                                   Table "public.social_auth_association"
   Column   |          Type          |                              Modifiers                               
------------+------------------------+----------------------------------------------------------------------
 id         | integer                | not null default nextval('social_auth_association_id_seq'::regclass)
 server_url | character varying(255) | not null
 handle     | character varying(255) | not null
 secret     | character varying(255) | not null
 issued     | integer                | not null
 lifetime   | integer                | not null
 assoc_type | character varying(64)  | not null
Indexes:
    "social_auth_association_pkey" PRIMARY KEY, btree (id)


chipy_org=# \d social_auth_nonce;
                                   Table "public.social_auth_nonce"
   Column   |          Type          |                           Modifiers                            
------------+------------------------+----------------------------------------------------------------
 id         | integer                | not null default nextval('social_auth_nonce_id_seq'::regclass)
 server_url | character varying(255) | not null
 timestamp  | integer                | not null
 salt       | character varying(40)  | not null
Indexes:
    "social_auth_nonce_pkey" PRIMARY KEY, btree (id)


chipy_org=# \d social_auth_usersocialauth;
                                   Table "public.social_auth_usersocialauth"
   Column   |          Type          |                                Modifiers                                
------------+------------------------+-------------------------------------------------------------------------
 id         | integer                | not null default nextval('social_auth_usersocialauth_id_seq'::regclass)
 user_id    | integer                | not null
 provider   | character varying(32)  | not null
 uid        | character varying(255) | not null
 extra_data | text                   | not null
Indexes:
    "social_auth_usersocialauth_pkey" PRIMARY KEY, btree (id)
    "social_auth_usersocialauth_provider_uid_key" UNIQUE CONSTRAINT, btree (provider, uid)
    "social_auth_usersocialauth_user_id" btree (user_id)
Foreign-key constraints:
    "social_auth_usersocial_user_id_193b2d80880502b2_fk_auth_user_id" FOREIGN KEY (user_id) REFERENCES auth_user(id) DEFERRABLE INITIALLY DEFERRED


chipy_org=# \d social_auth_usersocialauth_user_id 
Index "public.social_auth_usersocialauth_user_id"
 Column  |  Type   | Definition 
---------+---------+------------
 user_id | integer | user_id
btree, for table "public.social_auth_usersocialauth"
```

**Comment by emperorcezar** [comment]
I agree, from a scan or the two, looks like the only thing missing is the
social_auth_code table. We should be able to create that and just fake the
migration.

-------------------------------------------------------------------------------------------------------------
Father, Pythonista, Cyclist, Brewer. Dabbling in Clojure and Functional
Languages

**Comment by elmq0022** [comment]
@raymondberg this is really old, but do we run the risk of breaking any links to user data?

**Comment by elmq0022** [comment]
Upgraded to python 3 and resolved python social auth.
