### ISSUE TITLE
Update Imaginary Landscape's logo

### ISSUE THREAD

**Issue by tathagata** [chicagopython/chipy.org#149]
![image](https://cloud.githubusercontent.com/assets/68151/25925806/9b66e0bc-35b0-11e7-9a14-60bb235a6aab.png)

**Comment by JoeJasinski** [comment]
I did this on the main website. @brianray this should be done on the slides as well.

**Comment by JoeJasinski** [comment]
Closing this since it's been updated on the site.  @adambain-vokal I can't remember if this logo made it to the slides, but might want to reference this ticket if it has not.
