### ISSUE TITLE
Short urls from chipy.org

### ISSUE THREAD

**Issue by tathagata** [chicagopython/chipy.org#152]
Chipy does a lot of things these days and we need an easy way to redirect people where they can find more information. Short urls make this very easy. Following are the ones that I have felt the need for - please add the ones that you can think of:

- python project nights 
chipy.org/ppn -> https://github.com/chicagopython/CodingWorkshops  

- code of conduct
chipy.org/coc -> http://www.chipy.org/pages/conduct/

- slack
chipy.org/slack -> https://chipy.slack.com/messages/general
[ @adeolapure please 👍  or 👎  ]

- chipy.org/mentor -> chipymentor.org  
[Mentorship is the most frequently asked, @raymondberg please 👍  or 👎  ]

@jasonwirth does finsig have/need any?
@JoeJasinski what about webdev

These can just be http redirects, I'm not asking of a full fledged url shortening *micro*service.

**Comment by jasonwirth** [comment]
Short URLs are good for slides and presentation, but a better solution would be making the website more usable. Sorry to say it, but my brain is so worthless that I'm never going to remember a URL, no matter how short, other than chipy.org.

**Comment by raymondberg** [comment]
I'm fine with this in slides as long as we never use these URLs for navigation.

**Comment by adeolapure** [comment]
That all makes sense to me! and +1 x 2 re: Jason and Ray

**Comment by emperorcezar** [comment]
@JoeJasinski does your PR help with this?

**Comment by JoeJasinski** [comment]
The PR adds some general improvements to navigation and brings forward more links to the homepage.  Check out chipy-dev.herokuapp.com

**Comment by JoeJasinski** [comment]
Let me know when that PR is ready for merging .  I have a Django 1.11 update built on top of that

**Comment by elmq0022** [comment]
Stale.  Closing issue.
