### ISSUE TITLE
Expire Announcements, add placeholder 

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#154]
<img width="739" alt="screen shot 2017-09-08 at 2 26 38 pm" src="https://user-images.githubusercontent.com/676284/30225856-f810db92-94a1-11e7-8182-696bceee97a8.png">

It's not Sept 8th and the announcement from over a month ago is hagning there.

**Comment by JoeJasinski** [comment]
@brianray this is the "announcement", which lets us put general announcements on the front page.  Adding a new one should push this one off to the archive. Maybe we could add another feature to expire announcements from showing up on the main page. 

I hope people use this feature; it was intended to make it easier to make one-off free-form announcements like the Pololyglot or ULS or similar.

**Comment by JoeJasinski** [comment]
@brianray @emperorcezar 

Pull request to add the end_date on announcement. Read for review. 

https://github.com/chicagopython/chipy.org/pull/156

**Comment by JoeJasinski** [comment]
This is deployed btw
