### ISSUE TITLE
host a meeting page empty

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#155]
Should this say something?

<img width="1440" alt="screen shot 2017-09-08 at 2 30 27 pm" src="https://user-images.githubusercontent.com/676284/30225998-75ff475a-94a2-11e7-88df-8f06390b776a.png">

**Comment by JoeJasinski** [comment]
Ya, both of these flatpages need some content.  Presumedly info on how a potential host can get involved.  The other link would be for how to donate to ChiPy.


http://www.chipy.org/admin/flatpages/flatpage/16/
http://www.chipy.org/admin/flatpages/flatpage/17/

**Comment by JoeJasinski** [comment]
@patrickboland4 since you've pulled in some recent hosts, is there anything that might be useful to add to this page?

**Comment by elmq0022** [comment]
This has been corrected.
