### ISSUE TITLE
Install SSL Cert

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#157]
Would be great to get an SSL cert setup for this.  We'll likely need to upgrade to Hobby plan to do this. 

@brianray

**Comment by JamesJeffryes** [comment]
FWIW it looks like Cloudflare's free plan includes a shared SSL cert so a heroku upgrade may not be necessary. Here's a walkthough: https://medium.freecodecamp.org/free-https-c051ca570324

**Comment by JoeJasinski** [comment]
Closing this issue since we added SSL a few months back.
