### ISSUE TITLE
Something is wrong with the annoucment

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#158]
See Screen shot. It still says October and does not match the next meeting.

<img width="1058" alt="screen shot 2017-10-26 at 9 44 51 am" src="https://user-images.githubusercontent.com/676284/32056364-780f014c-ba32-11e7-9250-95fe137da25e.png">

**Comment by JoeJasinski** [comment]
It just needed an end date added to the record in the Admin. I've added an end date to every announcement via the Django admin, except for one "default" message that will appear in the case that all other messages are expired.
