### ISSUE TITLE
Meeting Description field needs to support rich text formatting

### ISSUE THREAD

**Issue by tathagata** [chicagopython/chipy.org#167]
As an event organizer, I want to include rich text in the meeting descriptions, so that I can include links and other formatting such that it makes reading easier.

Project Night is moving to chipy.org for RSVPs. We need to provide multiple instructions for our attendees - on what to bring, what to expect, agenda/timeline, FAQs. example:
https://www.meetup.com/_ChiPy_/events/gdqnkqyzcbwb/
The current description field does not support the formatting needed for organizing such long content and it renders it as a blob of text, very difficult to read.
Supporting rich-text would allow adding the description properly.

**Comment by JoeJasinski** [comment]
Projects to consider:
https://djangopackages.org/packages/p/django-ckeditor/
https://djangopackages.org/packages/p/django-tinymce/
