### ISSUE TITLE
Summary for sponsors to see how many attendees attended each event

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#171]
As a ChiPy sponsor, I want to see a summary of attendance for past meetings so I can convince my steakholders to sponsor ChiPy. 

@grybox mentioned that it would be great to have a summary page that shows how many attendees attended the past X number of ChiPy events, so sponsors can see how many people are engaging with ChiPy.

**Comment by JoeJasinski** [comment]
Maybe we can add this to the top of (or as a link on) the ChiPy Sponsor page.

**Comment by raymondberg** [comment]
It sounds like @smandekar1 is interested in this!

**Comment by smandekar1** [comment]
Created PR that tabulates and displays RSVPs from the past year.  
<img width="1009" alt="Screen Shot 2019-09-20 at 3 20 24 PM" src="https://user-images.githubusercontent.com/11667547/65356484-36205780-dbba-11e9-8c14-b1c583170a11.png">

**Comment by elmq0022** [comment]
@JoeJasinski I like the idea of having metrics.  A fair portion of the chipy community has a data slant anyway.  

I feel a nice summary page (dashboard) with graphs of relavent meeting information could be really useful.  

What would be useful / impressive to sponsors beyond meeting attendance? Maybe the following?
- mentorships completed
- SIGs
- job placement
- first time chipy participants

This might all be good for the organization as a whole.

**Comment by elmq0022** [comment]
Addressed in pull request #202
