### ISSUE TITLE
The upcoming events on the homepage should not be so long

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#173]
As a ChiPy event scheduler, I want to be able to enter a lot of detailed information for an event, without it consuming so much space on the homepage and instead show it on the event detail page, so that the esthetic of the homepage is not disrupted. 

Currently on the ChiPy homepage "Upcoming Events" section, if an admin enters a really large description, the box stretches really tall and takes up too much space.  Two options to solve:

 1. truncate the paragraph if it's too long. Really easy and effective. See below
    https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#truncatechars
    https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#truncatechars-html
    https://docs.djangoproject.com/en/2.1/ref/templates/builtins/#truncatewords-html
 2. use the same javascript [more] dropdown that we use for "This Month's Topics" on the hompage.

**Comment by smandekar1** [comment]
fixed with truncatewords_html on homepage.  Believe this can be closed

**Comment by elmq0022** [comment]
Awesome 👍
