### ISSUE TITLE
Add a Meeting Title to the Meeting object

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#174]
As a site admin, I want to add a custom title to each meeting so that I can convey more info about the meeting similar to meetup.com.

Example:
"ChiPy 2019 January Main Meeting: Ultimate Language Shootout"

Acceptance Criteria: 
- This should display on the homepage as well as on the meeting detail page.
- This should integrate nicely with the current design.
- This should not be a required field and should not look ugly if the admin does not fill it out.
- The title should be made visible in the meeting dropdown on the Speaker submit page. (note: see the __str__ / __unicode__ method on the Model)
- The title should be made visible in the Django admin meeting list page.

Notes:
This will require a new non-required field on the Meetings table and have django database migrations to support it.

**Comment by elmq0022** [comment]
Same as #218
