### ISSUE TITLE
Mobile Registration Refactor

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#175]
As a mobile ChiPy attendee, I want to be able to easily register from my phone, so I can sign up for ChiPy events on the go.

Right now, the mobile registration workflow for anonymous users is very difficult. The current Javascript popup is not mobile friendly. This is not as much of an issue for logged-in users.

**Comment by tathagata** [comment]
@bhchance this looks like the right issue for some one with frontend expertise.

**Comment by obf73** [comment]
I just issued a pr for this.  the branch is bugfix/mobile-registration-refactor

**Comment by tathagata** [comment]
@obf73 thanks a lot! Thanks to @JoeJasinski the changes have been deployed - I was able to rsvp from safari on ios, I'll check on slack if someone can do a quick verification from an android based browser and we'll be good to close this out. Thanks once again!

**Comment by tathagata** [comment]
Greg_B on slack verified with an Android device! 🎉
