### ISSUE TITLE
Update check list for talk submission to include code of conduct references

### ISSUE THREAD

**Issue by tathagata** [chicagopython/chipy.org#183]
As an organizer
in order to prevent code of conduct violation by speakers
I would like the talk submission page to include relevant references to out code of conduct

related: #111

**Comment by tathagata** [comment]
@raymondberg please take a look if you would want any additional details.

**Comment by raymondberg** [comment]
❤️  this

Something like:

> [ ] I have read ChiPy's Code of Conduct and will ensure my presentation and associated materials (slides, handouts, etc...) do not violate the Code of Conduct.
