### ISSUE TITLE
Bad Alignment on  Sponsor List Page for Sponsors without Logo

### ISSUE THREAD

**Issue by elmq0022** [chicagopython/chipy.org#216]
Alignment is not good for chipy.org/sponsor/list that do not have a logo, viz Apex systems below. 

![image](https://user-images.githubusercontent.com/3450848/69698819-5243f600-1121-11ea-8b26-dc588da3f37a.png)

**Comment by sophm256** [comment]
I'm going to work on this.

**Comment by sophm256** [comment]
**How do I get the logos/pics to show up on the sponsor_list.html?** I went to the admin page. Then filled out the 'sponsor' form and uploaded a picture for the logo .  When I went to visit the sponsor_list page in the browser, I got an error message saying that I didn't have permission for the mediafiles directory. I created that directory and changed the permissions, which made the error go away.  But I still do not see any pictures (that I uploaded) on 'sponsor_list.html'.

![sponsor-list](https://user-images.githubusercontent.com/53249319/73194909-87a19b80-40f2-11ea-9a06-f252fad68220.JPG)
....................................................................................................................................
I got the 3rd sponsor to show up correctly. That sponsor does not have a logo associated with it. The 2nd sponsor does have a logo associated with it, but it doesn't show up in the html at all. Here's a portion of the html code for the 3rd and 2nd sponsor.
![sponsor-code](https://user-images.githubusercontent.com/53249319/73195179-08609780-40f3-11ea-824c-03dfc858cfc3.JPG)
......................................

Using the bash shell, I navigated to '/site/proj/chipy_org/mediafiles' to see if the logo file was there and it was. So how can I get the image to show up? I know it's using the sorl thumbnail library. Is there a setting I need to do, like setting a cache?  Thanks, much obliged.

**Comment by elmq0022** [comment]
I got this to work locally by:

1. in docker.env set USE_S3=False
2. made a directory `mediafiles` to store images
3. gave the user app permission to write files in `mediafiles`  
4. created a sponsor with an image
5. created a general sponsor
6. created a sponsor group.  

By doing this I got an image for the sponsor on:
1. the homepage
2. the sponsor list view
3. the sponsor detail view 

![image](https://user-images.githubusercontent.com/3450848/73902494-abd04b80-485b-11ea-8971-4d958ceae469.png)

![image](https://user-images.githubusercontent.com/3450848/73902546-ca364700-485b-11ea-92b0-fabfd92ab5d5.png)

![image](https://user-images.githubusercontent.com/3450848/73902587-ea660600-485b-11ea-8438-c7a35e6e8157.png)

We can talk about this one a little more at the web-guild meeting.  

You mentioned, on slack, that in the docker-compose.yml file USE_S3=False. I think we should look into that. This doesn't seem quite right to me. We both verified this change was introduced in March 2019 with commit 364730.

A quick check on the wayback machine https://web.archive.org/web/20190924062334/https://www.chipy.org/ shows images were on S3 as late as September 24th, 2019.  

https://web.archive.org/web/20190213205848im_/https://chipy.s3.amazonaws.com/cache/8a/06/8a06c47d578ab2dbe4529138a03aae81.jpg

If you want to continue to work on this one, that's fine.  However just realize it won't effect any change until we put sponsor images back on the site.

**Comment by sophm256** [comment]
Nice job on getting it to work! :cake: I'm still in the middle of setting it up. 

Yes, we can talk more about USE_S3 at the meeting as it may be redundant to be defining it in two different places.

**Comment by sophm256** [comment]
There is also a possibility that those images online are being served from a folder called 'mediafiles' on Heroku instead of from S3. And maybe the reason one no longer sees them is a permissions issue on that folder, the folder was deleted, or the images were deleted.

**Comment by sophm256** [comment]
I followed your setup and still can't see logos. I think I'm going to put this aside for now. If you could help me get it working at the web-guild meeting, that would great.

**Comment by elmq0022** [comment]
Sure thing 👍

**Comment by sophm256** [comment]
For anyone wondering, I have gotten the logos to show up. I was using a .png file which was not showing up, but when I used a .jpg, it did show up.

**Comment by elmq0022** [comment]
Adding a note to the admin about using jpg vs a png would be nice. Being
able to use a png as well would be better.  We have the pillow package
installed already, so converting the png to a jpg should be straight
forward.

**Comment by elmq0022** [comment]
@sophm256 do you want to continue working on this one?  Let me know if you have any questions.

**Comment by sophm256** [comment]
@elmq0022 Yes, I'll continue to work on this one. It should be simple as long as the images show up.

**Comment by sophm256** [comment]
I tested the most recently deployed version of chipy by adding logos to the sponsor list page. I had some of the sponsors be without logos.  And the alignment issues have magically fixed themselves. It has been tested in firefox and chrome. It's up to you if you want to close this issue. If the issue comes up again in the future, I can fix it. But as is, it works.

![alignment-logo-3-23-2020](https://user-images.githubusercontent.com/53249319/77319161-57364200-6cdc-11ea-8893-5e6dcafa5816.JPG)

**Comment by elmq0022** [comment]
Wow.  What a wild goose chase this was.  Probably related to all the thumbnail storages issues.  

Thanks @sophm256 

Closed
