### ISSUE TITLE
Talks Submission Email Not working

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#248]
I've been noticing that the Talk submission email is no longer getting sent (since around November). 

This is the email that gets sent:
https://www.chipy.org/meetings/topics/propose/

**Comment by elmq0022** [comment]
I will try to take a look into it this  weekend.  Thanks for the heads up.

**Comment by smandekar1** [comment]
may need {% load bleach_tags %} on meeting_topic_submitted.html, but still get ModuleNotFoundError: No module named "'django" in logs

**Comment by elmq0022** [comment]
thanks @smandekar1 could you drop the log message here for documentation purposes.

**Comment by smandekar1** [comment]
```    File "/home/app/.local/lib/python3.6/site-packages/django/utils/module_loading.py", line 26, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named "'django"
[pid: 9|app: 0|req: 32/57] 172.19.0.1 () {54 vars in 1183 bytes} [Thu Jan 23 22:43:52 2020] POST /meetings/topics/propose/ => generated 0 bytes in 71 msecs (HTTP/1.1 302) 5 headers in 270 bytes (1 switches on core 0)
```

Also, I'm not getting rsvp email confirmations

**Comment by elmq0022** [comment]
@smandekar1 do you want to work on the fix for this?   I could write a couple tests to check for proper email functionality instead.

**Comment by elmq0022** [comment]
RSVP emails are working in production for anonymous RSVPs.   l don't believe we email users that are logged in.

**Comment by smandekar1** [comment]
Ok, that makes sense then, logged in users don't get emailed and anonymous rspvs are working.  I may not get to work on the issue for a few days, but I can do it.  If you know the solution offhand, go ahead and do it.

**Comment by elmq0022** [comment]
I'll reply here if I star working on it.

**Comment by elmq0022** [comment]
Yes, the load bleach tag was missing.  I made the addtion and and the output of grep for bleach after the fact is shown below.  

<pre>zero@debian:~/Python-Projects/chipy.org$ grep -R -i bleach .
<font color="#D33682">./chipy_org/templates/homepage.html</font><font color="#2AA198">:</font>{% load <font color="#CB4B16"><b>bleach</b></font>_tags %}
<font color="#D33682">./chipy_org/templates/homepage.html</font><font color="#2AA198">:</font>                      {{ topic.description|striptags|truncatewords:80|<font color="#CB4B16"><b>bleach</b></font>|safe }}&lt;br /&gt;
<font color="#D33682">./chipy_org/settings.py</font><font color="#2AA198">:</font>    &apos;django_<font color="#CB4B16"><b>bleach</b></font>&apos;,
<font color="#D33682">./chipy_org/settings.py</font><font color="#2AA198">:</font><font color="#CB4B16"><b>BLEACH</b></font>_ALLOWED_TAGS = [&apos;p&apos;, &apos;b&apos;, &apos;i&apos;, &apos;u&apos;, &apos;em&apos;, &apos;code&apos;, &apos;strong&apos;, &apos;a&apos;, &apos;span&apos;, &apos;tt&apos;, &apos;hr&apos;, &apos;img&apos;,
<font color="#D33682">./chipy_org/settings.py</font><font color="#2AA198">:</font><font color="#CB4B16"><b>BLEACH</b></font>_ALLOWED_ATTRIBUTES = [&apos;href&apos;, &apos;title&apos;, &apos;style&apos;, &apos;rel&apos;, &apos;img&apos;, &apos;src&apos;, &apos;alt&apos;]
<font color="#D33682">./chipy_org/settings.py</font><font color="#2AA198">:</font><font color="#CB4B16"><b>BLEACH</b></font>_ALLOWED_PROTOCOLS = [&apos;http&apos;, &apos;https&apos;, &apos;data&apos;]
<font color="#D33682">./chipy_org/settings.py</font><font color="#2AA198">:</font><font color="#CB4B16"><b>BLEACH</b></font>_ALLOWED_STYLES = [&apos;font-family&apos;, &apos;font-weight&apos;, &apos;text-decoration&apos;, &apos;font-variant&apos;]
<font color="#D33682">./chipy_org/settings.py</font><font color="#2AA198">:</font><font color="#CB4B16"><b>BLEACH</b></font>_STRIP_TAGS = True
<font color="#D33682">./chipy_org/apps/meetings/templates/meetings/meeting.html</font><font color="#2AA198">:</font>{% load <font color="#CB4B16"><b>bleach</b></font>_tags %}
<font color="#D33682">./chipy_org/apps/meetings/templates/meetings/meeting.html</font><font color="#2AA198">:</font>          &lt;p itemprop=&quot;description&quot;&gt;{{ meeting.description|<font color="#CB4B16"><b>bleach</b></font>|safe }}&lt;/p&gt;
<font color="#D33682">./chipy_org/apps/meetings/templates/meetings/meeting.html</font><font color="#2AA198">:</font>                  Description: {{ topic.description|<font color="#CB4B16"><b>bleach</b></font>|safe }}
<font color="#D33682">./chipy_org/apps/meetings/templates/meetings/_talk.html</font><font color="#2AA198">:</font>{% load <font color="#CB4B16"><b>bleach</b></font>_tags %}
<font color="#D33682">./chipy_org/apps/meetings/templates/meetings/_talk.html</font><font color="#2AA198">:</font>          {{ talk.description|<font color="#CB4B16"><b>bleach</b></font>|safe }}
<font color="#D33682">./chipy_org/apps/meetings/templates/meetings/emails/meeting_topic_submitted.html</font><font color="#2AA198">:</font>{% load <font color="#CB4B16"><b>bleach</b></font>_tags %}
<font color="#D33682">./chipy_org/apps/meetings/templates/meetings/emails/meeting_topic_submitted.html</font><font color="#2AA198">:</font>&lt;p&gt;Description: {{ topic.description|<font color="#CB4B16"><b>bleach</b></font>|safe }}&lt;/p&gt;
<font color="#D33682">./requirements.txt</font><font color="#2AA198">:</font>django-<font color="#CB4B16"><b>bleach</b></font>==0.6.1 
</pre>

I'll make a quick pull request so we can push this to production as soon as possible, but we should still add tests for the email.  I stepped through code and this will work.

**Comment by smandekar1** [comment]
That sounds good, glad it's working.

**Comment by elmq0022** [comment]
@JoeJasinski code fix was merged.  Let me know if you see any issues with the live site.  Thanks!

**Comment by JoeJasinski** [comment]
Thank you @elmq0022 and @smandekar1, I saw an email come through today

**Comment by elmq0022** [comment]
Awesome 👍

**Comment by smandekar1** [comment]
Great!
