### ISSUE TITLE
Subtitles on homepage are links that lead to nowhere 

### ISSUE THREAD

**Issue by sophm256** [chicagopython/chipy.org#251]
Subtitles on homepage.html are clickable links that don't lead to anywhere. They are 
"Next Main Meeting", "Upcoming Events", "About", "Participate", "Sponsors".  Should they be converted from "\<a\>" tags to "div" tags so that they are no longer links? (Perhaps, we would leave the "Upcoming Events" as a link because someone who'd work on issue #178 could use that.)  But all other links could be converted to regular text?

**Comment by elmq0022** [comment]
I would leave these as links as they are used for navigation.  For example the about link at the top of the main page moves to the about section of the page.  

However, the default CSS that make these look like navigation links is confusing.  Maybe CSS could be used to style this so they don't appear to be clickable links that lead to nowhere.

**Comment by sophm256** [comment]
Yes, but it's possible to remove the links and still be able to use them for navigation. 

For example, if the 'about' link on the top nav bar links to `https://www.chipy.org/#about` which is the 'About' section in the body.

In the subheading 'About', the code looks like.

```
<div class="row-fluid">
            <div class="module span12"><h2><a name="about">About</a></h2></div>
        </div><!-- #row-fluid -->
<div class="row-fluid">
```

You could change the 'a' tags to 'div'. This will still allow the 'about' nav link to reference the 'about' section of the page because of  `name="about'`. This subheading 'About' does not have to be a link. Also no further special css is needed to fix how it looks. It'll look like it currently looks but without an underline when you hover over it. 

```
<div class="row-fluid">
            <div class="module span12"><h2><div name="about">About</div></h2></div>
        </div><!-- #row-fluid -->
<div class="row-fluid">
```

If you agree with this solution, would you want to change all of the links or leave the "Upcoming Events" as a link?

**Comment by elmq0022** [comment]
If you can make it work that way, sure.  I will approve the update if it
looks good and doesn't break existing functionality.  😉
