### ISSUE TITLE
Add "volunteer" nav link as submenu item under "support us"

### ISSUE THREAD

**Issue by sophm256** [chicagopython/chipy.org#255]
To encourage volunteering, we can create a"volunteer" nav link as a submenu item under "support us"

I have written the web guild blurb as:  https://gist.github.com/sophm256/9a8937a8e61c553356afd117e95b5110

Please let me know if you'd like me to make any changes. Thanks!

**Comment by raymondberg** [comment]
This looks great to me! The key is to make a link to a flat-page. I kind of wish we could make a database-driven nav bar instead of needing to deploy every time we change it.

**Comment by sophm256** [comment]
Thanks Ray for reading it over!

**Comment by raymondberg** [comment]
This is live! Thanks for the great idea, @sophm256.
