### ISSUE TITLE
Propose Topic -- make length required

### ISSUE THREAD

**Issue by alysivji** [chicagopython/chipy.org#258]
As an organizer, talk lengths help me plan schedules. Should make `Length minutes (optional)` a required field.

This is the page: https://www.chipy.org/meetings/topics/propose/

#### Definition of Done

- form cannot be submitted without a length
- remove optional from form text

**Comment by JoeJasinski** [comment]
What about if we were to have a setting on the meeting where we enforce the length or not? (I.e. if they select a meeting from the dropdown and the meeting has a length required - which we could default to on - then they would be required to enter a length). Some cases it's more important than others to have an exact length at the beginning?

**Comment by elmq0022** [comment]
I would just require an estimate.  Not that hard to type am estimate.
Personally, I favor less complexity.

**Comment by JoeJasinski** [comment]
Above is a PR that should address this.

**Comment by alysivji** [comment]
Closed by #274
