### ISSUE TITLE
Sponsor Icons on HomePage missing and Images missing on sponsors page

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#259]
I noticed that the Sponsor Logos are no longer showing up on the Homepage and the Sponsor images are no longer visible on the Sponsor List and Detail pages

https://www.chipy.org/sponsors/detail/
https://www.chipy.org/sponsors/detail/imagescape/

It's a nice selling point to our sponsors to have their logos and information there.

**Comment by elmq0022** [comment]
Yeah. I opened an issue for this previously.  I am not sure how this
happened.  I tried it on a dev site and the code seems to be working.
Maybe just need to add the icons back to the admin now that I think about
it.

**Comment by elmq0022** [comment]
Adding to existing issue, #246.
