### ISSUE TITLE
Add URL for remote events

### ISSUE THREAD

**Issue by alysivji** [chicagopython/chipy.org#275]
Now that ChiPy is all in for remote events we should start making the experience a bit more frictionless for our community.

Currently, we are sharing links to online events on Slack and in the ChiPy.org Announcements at the top. I think it would also be good to share a link in the event itself.

Current event layout:

![image](https://user-images.githubusercontent.com/4369343/79484625-94d77380-7fd9-11ea-9a19-529a155e0776.png)

When I click the Remote Meeting link, it opens up a modal:
![image](https://user-images.githubusercontent.com/4369343/79484759-c51f1200-7fd9-11ea-940d-43704506a59d.png)

Can't recall what this opens up for iin-person events. For remote events, it would be handy to just link that text to the event URL.

#### Acceptence Criteria

- organizers can specify the event is remote
- organizers are able to provide a link to the event
- displayed event has link in event details

**Comment by elmq0022** [comment]
This will be a good add.  Will try to take a look this weekend.

**Comment by alysivji** [comment]
Related to this, can we add a link to our YouTube channel in the participate section?

![image](https://user-images.githubusercontent.com/4369343/79615844-3984ae80-80c9-11ea-8881-c97388fe28f4.png)

URL: https://bit.ly/chipy-tube

**Comment by elmq0022** [comment]
@alysivji is there a reason we aren't using the live stream field (which already exists) for this request?  If we can use that then nothing needs to change.  Let me know.  Thanks.

![screen](https://user-images.githubusercontent.com/3450848/80311944-2ac48880-87a8-11ea-996a-ac51ea9bf031.png)

**Comment by elmq0022** [comment]
Will look at adding youtube as well.

**Comment by alysivji** [comment]
Had no idea we had a livestream field...! Thanks @elmq0022!

This works without having to do any work.

![image](https://user-images.githubusercontent.com/4369343/80312316-34e78680-87aa-11ea-9404-757e58f5df11.png)


If you are working on this today, it would be nice if we can clean this up a bit with Remote meetings not having a link. Would only be the one livestream link

**Comment by elmq0022** [comment]
@alysivji that's great to hear!  Glad it works.  Also I added a link our YouTube using this url: 

https://www.youtube.com/channel/UCT372EAC1orBOSUd2fsA8WA

If we need it linked to some other location please let me know prior to 6PM on Tuesday (April 28th) as we plan to push this with the Django 2.2 deploy that evening.  

Thanks!

**Comment by alysivji** [comment]
That URL works!

**Comment by elmq0022** [comment]
Great!

**Comment by elmq0022** [comment]
Closed by #277
