### ISSUE TITLE
[Job Board] Post approved jobs to Slack

### ISSUE THREAD

**Issue by alysivji** [chicagopython/chipy.org#319]
As an admin, I would like jobs I approve on the ChiPy job board to be posted to the ChiPy Slack jobs channel. We can guarantee uses agree to our Referral Policy when they submit jobs via our website.

#### Definition of Done

- post job when it is approved
  - job should only be posted once, no matter how many times it is approved
- create a template (maybe using Slack Block Kit) for Slack job postings
- post messages using an API webhook
  - will need to explore this a bit more; my initial thought is that we should create a ChiPy bot for these kinds of tasks
  - Busy Beaver is a Slack Integration that can be used by other users groups. While there are still some features that are ChiPy Slack only, the majority of features can be used by all installations

**Comment by elmq0022** [comment]
@alysivji we have all approved jobs posted to slack once a week on Wednesdays. 

Does this cover the use case, or should new jobs posted immediately when first approved as well?

**Comment by alysivji** [comment]
Weekly posting totally covers the use case I was thinking about. Closing this issue
