### ISSUE TITLE
Change Upcoming events to "Train Stop" interface

### ISSUE THREAD

**Issue by raymondberg** [chicagopython/chipy.org#359]
There's this really cool interface that was part of the original design, but was too complex to implement quickly. We'd love to see it replace the "Upcoming meetings page"

![image](https://user-images.githubusercontent.com/5155488/107708196-b69c9800-6c88-11eb-8f20-ec527b3c1b85.png)

Requirements
* Show minimum of one event in the past (possibly two if you think it looks better)
* Show up to 4 events in the future (use judgement)
* Alternating sides of the track per the design
* Line/Dot connecting to the center
* Link to "All Upcoming events (List View)" at the bottom takes you the current (boring) page

Nice to haves
* Figuring an easy way to do RSVPs would be nice (and to show that someone had RSVP'd for each event). In the interim, each button should say "INFO" or "LEARN MORE". Something like that.

Best to start from scratch on the assets here.

**Comment by sophm256** [comment]
I will take a shot at working on this.
