### ISSUE TITLE
Display Upcoming Events in REVERSE cronological order

### ISSUE THREAD

**Issue by raymondberg** [chicagopython/chipy.org#366]
Definitions:
  soonest - the meeting that is happening sooner than all other meetings
  furthest - the meeting that is happening later than all other meetings

Right now the [upcoming events page](https://www.chipy.org/meetings/) displays the furthest future meeting first, and the most pressing, soonest meeting last. 🤦 <- me having done that 

We should, of course, list them in reverse order: soonest at top, furthest at bottom.

**Comment by tym-xqo** [comment]
This looks to me like perhaps it got fixed at some point? Maybe this could be closed?

<img width="639" alt="Screen Shot 2021-03-19 at 18 39 40" src="https://user-images.githubusercontent.com/10351894/111851759-89c04e00-88e2-11eb-9c90-f3e5336e37f0.png">

**Comment by elmq0022** [comment]
Thanks @tym-xqo - this is stale.  I'll close these to help people know what still needs to be done.
