### ISSUE TITLE
Clarify docker download and start instructions in README

### ISSUE THREAD

**Issue by patrickboland4** [chicagopython/chipy.org#383]
After downloading docker and docker-compose, I followed along the README, until `$ make up` produced the following: 

``` sh
chipy.org MacBook-Pro-3:chipy.org patrickboland4$ make up
docker-compose up -d
make: docker-compose: Permission denied
make: *** [up] Error 1
```

I received the same error after running `$ sudo make up`. 

The solution was, I needed to run the docker application on my Mac, which prompted me for the root password. 

I'd like to provide just a bit more clarity around starting Docker, especially for folks who are less familiar with Docker (like me).

**Comment by elmq0022** [comment]
Yes, we should definitely do that.  I don't have a mac to test on so help
there would be appreciated. I can add additional information for linux and
windows prior to WSL.
