### ISSUE TITLE
Revise README instructions for windows users

### ISSUE THREAD

**Issue by sophm256** [chicagopython/chipy.org#385]
Docker Toolbox is now deprecated. 

- Revise instructions for  "For Windows 7 to 10 Non Pro, 64-bit" to install Docker Desktop according to the link https://docs.docker.com/docker-for-windows/install-windows-home/
 (this installation includes  Docker and Docker Compose)

- Revise instructions for  "For Windows 10 Pro, 64-bit"  to install Docker  Desktop  according to link  https://docs.docker.com/docker-for-windows/install/  (this installation  includes  Docker and Docker Compose)

- Remove section "Instructions for Windows 7 to 10 Users (Non Pro)"

**Comment by nickymarino** [comment]
@sophm256 I think this can be closed since #402 is merged
