### ISSUE TITLE
Change README to add instructions for 'make dev-data'

### ISSUE THREAD

**Issue by sophm256** [chicagopython/chipy.org#393]
In README, add a section regarding 'make dev-data'. Say that if you want mock data for development, run 'make dev-data' after you have run 'make migrate' the first time. ('make migrate' creates your database tables, while 'dev-data' populates those tables with mock data.)

**Comment by nickymarino** [comment]
@sophm256 I think this can be closed since the README already has a `make dev-data` section: https://github.com/chicagopython/chipy.org/blame/main/README.md#L118-L122

**Comment by sophm256** [comment]
@Thanks @nickymarino . It looks like I can close this.
