### ISSUE TITLE
Add "IncBuilders Partnership Opportunity" to job board

### ISSUE THREAD

**Issue by eevelweezel** [chicagopython/chipy.org#401]
We want to be able to differentiate positions that are posted through our partnership with IncBuilders from other job postings.

Let's add a checkbox on the job posting form, with the text "This is an IncBuilders Partnership Opportunity".  If checked, let's display the text "IncBuilders Partnership Opportunity" on the posting and in the list view, maybe below the position and company name?  Or maybe, add it to the position field?

IncBuilders has requested the ability to submit postings via API, so they may integrate this with their platform. After looking at the view, it should theoretically be possible to POST to this endpoint as-is, with the caveat that we'd need to work out authentication.  I haven't really looked at the login_required decorator in a while, but maybe we could use basic-auth and an authentication header?

**Comment by elmq0022** [comment]
Hi @eevelweezel  - I added the the Inc Builder affiliation at the bottom of the Detail View.   I can add it to the list view as well if you like.  

I think you're right about posting directly with something like cURL.  We us OAuth2 with github and google as options for authorization.  So, I believe they would just have to pass their token in a cURL request.

If you think it's worth it, I could take a crack at adding a posting API with DRF.  I think we'd just need a serializer and another view to get that done. DRF is already part of chipy.org.
