### ISSUE TITLE
Sponsor Logos are not sized to width on mobile layout

### ISSUE THREAD

**Issue by elmq0022** [chicagopython/chipy.org#427]
Need some CSS or some other method limiting the image size to the mobile layout.  

![Screenshot_20211121-071101](https://user-images.githubusercontent.com/3450848/142763399-9b2b7045-0f6a-44de-bbea-d442851c698c.jpg)

**Comment by elmq0022** [comment]
@spark-c is this something you could pick up?   You seem pretty good with CSS.

**Comment by spark-c** [comment]
Sure thing!

**Comment by elmq0022** [comment]
Thanks! I would really appreciate that.  It's important that the site look
good especially for our sponsors.
