### ISSUE TITLE
Switch from norecaptcha-recaptcha to django-recaptcha

### ISSUE THREAD

**Issue by raymondberg** [chicagopython/chipy.org#432]
We used an unmaintained fork from Imaginary Landscape to get us through the recaptcha v2 conversion years ago, but it has no updates and cannot support Django 4.0. 

Switch to the standard django-recaptcha library and get our captchas working!

Check by running django with `python -Wd ...` to see whether you've fixed the issue.

**Comment by elmq0022** [comment]
hmmmm ... seems unmaintained 

https://github.com/praekelt/django-recaptcha/issues/244

will added it because it's easy and hope someone updates it or forks it.

**Comment by elmq0022** [comment]
we could move to simple captcha as well.
