### ISSUE TITLE
Fix sponsor wrapping on "Our Sponsors" page

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#464]
Our sponsor logos are wrapping weird when there are several on the same level. For example, Braintree and JFrog are on the same line and aren't aligned properly. We've had some comments

https://www.chipy.org/sponsors/list/
![image](https://user-images.githubusercontent.com/417872/157989080-5dbb8a30-5166-48ac-a9dd-c6fb7560d996.png)

**Comment by elmq0022** [comment]
I asume that's the case, not putting them on the same line.

**Comment by sophm256** [comment]
The simplest thing to do would be to put each logo on a different row. The code for when there is a logo and when there isn't a logo (text only of the comany) would need to be changed. I think, currently for Silver, it's trying to put all 3 logos on one row and the 3rd logo (Zoro) gets wrapped to the next row.

**Comment by sophm256** [comment]
I'll work on this.

**Comment by elmq0022** [comment]
Looks really nice.  Closed.
