### ISSUE TITLE
Pull RSVPs from Meetup.com

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#47]
Here are the features for the meetup.com integration:
- (MVF) automatically pull and push RSVP from one site to another. Chipy.org is the official
- allow publishing to pull or push the actual meeting settings (this is a nice to have, not required, we can always enter info twice)
- automatically subscribe users to the mailing list when the join the chipy.org site or meetup.com (again, nice to have)

**Comment by foresmac** [comment]
I'll pitch in any way I can, even if it's just code review or whatever.

**Comment by brianray** [comment]
Hey guys:  I met with the 5 of the ChiPy organizers today and we discussed this ticket. This is our top priority for 1st quarter this year. Thank you for the leadership on this. @emperorcezar and @foresmac did you guys want to take the leadership on this and give me some sort of development plan. It can be simple, however, I just want to take the stakeholder role here and I will report progress back to the group. Thanks again for doing this. 

Side note: we also want to establish that chipy.org should be our official record. We can push data from chipy.org like meeting schedule updates; however, the most important feature is the ability to refect and record RSVP on chipy.org that happen on meetup.com. Make sense?

**Comment by emperorcezar** [comment]
My plan  is to work on this during my train rides this week cause I'm
downtown four days.

I think step one is to pull rsvps from meetup.

So that's what I'm planning to work on this week.

**Comment by emperorcezar** [comment]
Forgot to mention. I don't see a reason  to have a big plan. I'm going to
ask that we break down our wanted features into individual issues on
github.

Once I have basic integration going with API keys ect. then anyone can pull
up and grab the other features.

**Comment by brianray** [comment]
no big plan can be a great plan, lol. I agree with breaking into individual issues. Please let me know what they are once you do it.

**Comment by emperorcezar** [comment]
- [ ] Setup Meetup API secret
- [ ] Make sure models can handle RSVPs without django users (this might already be the case because of anonymous RSVPs
- [ ] Setup something in the data model to store where the RSVP came from. Used to keep track of changes to RSVP. This might be just colliding on name.
- [ ] Figure out what to do with duplicates (Someone RSVPing in both places)
- [ ] Code up the piece used to call the meetup API and do the leg work
- [ ] Add a button for admins to force sync
- [ ] Find a way to run as a task. We're on heroku, so options are iron worker (10 free hours), or zapier and webhooks (I like this option, but need to pay for any reasonable amount of frequency.

**Comment by emperorcezar** [comment]
Just added support to the site. It's still pretty manual right now. Edit the meeting in the admin and add the meetup id of the meetup event. Then from the meetings list there is a button you can click to sync the RSVPs. They only go one way, from meetup into the site.

![screenshot 2015-02-01 00 14 29](https://cloud.githubusercontent.com/assets/68407/5991255/51fdbcbc-a9a7-11e4-840a-09b9d9018b54.png)

I've already synced for last month's meeting as a test bed.

**Comment by emperorcezar** [comment]
@brianray I added the meetup id for the upcoming meeting. The sync button will pull RSVPs from meetup into our list.

**Comment by brianray** [comment]
Cant wait to check it out

On Monday, February 9, 2015, emperorcezar <notifications@github.com> wrote:

> @brianray <https://github.com/brianray> I added the meetup id for the
> upcoming meeting. The sync button will pull RSVPs from meetup into our list.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chicagopython/chipy.org/issues/47#issuecomment-73644099>
> .
>


-- 
Brian Ray
@brianray
(773) 669-7717

**Comment by JoeJasinski** [comment]
I think we can call this done (since it's been working for years). If we want to run as task, we can open a new ticket for that.
