### ISSUE TITLE
Add Slack Invite Links to Portal

### ISSUE THREAD

**Issue by raymondberg** [chicagopython/chipy.org#477]
We used to have a nice free Heroku plugin. Then Heroku got all greedy and made free things go away. 

Old system: https://github.com/adeolapure/slack-invite-automation

We want to have a new integrated sign-in flow for getting into slack! Put it on the main site!

**Comment by JeffersGlass** [comment]
Is there any way to join the slack currently, without the automated plugin? I had been hoping to join the slack. 😄

**Comment by eevelweezel** [comment]
Right now, you need to ask an organizer to invite you. (I can do this if
you send me your email address.)

**Comment by raymondberg** [comment]
For now, you'll need to reach out to an organizer or community member or via the contact form if you want to get invited to slack.
