### ISSUE TITLE
Buddy Mentorship App

### ISSUE THREAD

**Issue by CarlFK** [chicagopython/chipy.org#486]
bottom of 
https://www.chipy.org/pages/volunteer/
are these words:

`Buddy Mentorship App`

I have no idea what that means.

**Comment by eevelweezel** [comment]
I wonder if this link got removed when chipymentor.org was taken off heroku?  At any rate, we should put the link back.

**Comment by raymondberg** [comment]
This is a flat page and not part of the django source code. I went into the admin panel and added some more information about that app.
