### ISSUE TITLE
upcoming_events shows previous evewnts 

### ISSUE THREAD

**Issue by CarlFK** [chicagopython/chipy.org#504]
https://www.chipy.org/meetings/upcoming_events/

Today Jun 26, it shows

1 Thursday JUN 2023 
8 Thursday JUN 2023 
6 Thursday JUL 2023

**Comment by raymondberg** [comment]
This is expected, when we get more meetings lined up it will be more obvious that we include the past two meetings intentionally to orient folks. They are greyed out but it's not as obvious with only one meeting

<img width="839" alt="image" src="https://github.com/chicagopython/chipy.org/assets/5155488/150d93e9-fc80-4d57-8481-eafe55b4969d">

**Comment by raymondberg** [comment]
I made it clearer that items are in the past with coloring and a go-nowhere button 
<img width="677" alt="image" src="https://github.com/chicagopython/chipy.org/assets/5155488/5b78ba3d-fd0f-433c-936f-fe89ec170943">
