### ISSUE TITLE
past meeting page has "submit a talk" link

### ISSUE THREAD

**Issue by CarlFK** [chicagopython/chipy.org#505]
https://www.chipy.org/meetings/228/
[Submit a Talk] (https://www.chipy.org/meetings/topics/propose/)
When: June 8, 2023, 6:30 p.m.

**Comment by eevelweezel** [comment]
Pretty sure I added this to the text of the meeting announcement. We could
go back and edit it, I don't have a strong opinion here.

**Comment by raymondberg** [comment]
Fixed by editing the meeting.
