### ISSUE TITLE
Submit a Talk link 404

### ISSUE THREAD

**Issue by CarlFK** [chicagopython/chipy.org#506]
assuming this is a thing for upcoming meetings (otherwise...umm.. mark Wont Fix!) 

https://www.chipy.org/meetings/228/
[Submit a Talk] (https://www.chipy.org/meetings/topics/propose/)
When: June 8, 2023, 6:30 p.m.

https://www.chipy.org/meetings/topics/propose 404
I'm guessing it should be 
https://www.chipy.org/talks/topics/propose/

**Comment by raymondberg** [comment]
Fixed by removing the link
