### ISSUE TITLE
add information on how to sponsor or host chipy events

### ISSUE THREAD

**Issue by codersquid** [chicagopython/chipy.org#52]
We have a page with venue requirements that was created by Carl a while back, but that is written from an AV perspective. We could have an informational page about hosting events that is more general. We could talk about different types of events and how sponsors can host each type of event, for example

* events with talks (like our monthly meetings)
* social events
* project nights
* sprints

Maybe this could be something that Asheesh might have as part of https://github.com/paulproteus/python-user-group-guide 

and then we could have an entry form for prospective hosts where they answer questions. also, we'd get a database of information about hosts that way.

**Comment by emperorcezar** [comment]
I believe someone already put up this page.
