### ISSUE TITLE
bugfix: dummy data produced by dev-data produces un-reversable meeting key

### ISSUE THREAD

**Issue by JoeJasinski** [chicagopython/chipy.org#529]
We get the following exception after loading the database with fake `make dev-data` because the script generates uuids for the meeting id. However, the model never does this in real life (it generates an alphanum), and the csv export cannot reverse this. 

<img width="1269" alt="image" src="https://github.com/chicagopython/chipy.org/assets/417872/06b3b03a-a43a-4172-879c-cc5d350e5d98">

**Comment by elmq0022** [comment]
@JoeJasinski can we close this one?

**Comment by JoeJasinski** [comment]
Yup, I'm closing now.
