### ISSUE TITLE
Add sender's email to messages from contact form

### ISSUE THREAD

**Issue by eevelweezel** [chicagopython/chipy.org#532]
When messages from the contact form are sent to chicago-organizers, there is no sender email with the message. This makes it really difficult to respond.

Could we add the sender's email to the message?

**Comment by elmq0022** [comment]
@eevelweezel  did you handle this?  I think I remember this being fixed.

**Comment by eevelweezel** [comment]
Yeah, I think this is a duplicate.

**Comment by elmq0022** [comment]
Thanks!
