### ISSUE TITLE
have rsvp questions

### ISSUE THREAD

**Issue by codersquid** [chicagopython/chipy.org#57]
Add a feature so that you can prompt for questions when people sign up, similarly to how meetup works.

Here are three questions I would ask, depending on whether a host needs ID for security and whether they offer food.
- Some hosts require a list of names for security. What is the name that appears on your ID?
- Some hosts sponsor food. Do you have any food preferences or concerns?
- Do you need any assistance related to accessibility?

**Comment by elmq0022** [comment]
We have the RSVP list implemented.
