### ISSUE TITLE
LOE of adding an Ad Box with click tracking

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#71]
Please let me know how much work it would be to add an banner add system to the main page of our website. It needs click tracking with all expected analytic. I am open to approach suggestions.

Wait for ChiPy Board approval before writing any code.

**Comment by emperorcezar** [comment]
Any updates on this?

**Comment by tanyaschlusser** [comment]
What about a PayPal donate button instead?
https://www.paypal.com/webapps/mpp/get-started/donate-button

**Comment by emperorcezar** [comment]
This seems to have stalled. Gonna wonfix this for now.
