### ISSUE TITLE
Page about ChiPy's Professional Placements and Recruiting

### ISSUE THREAD

**Issue by tathagata** [chicagopython/chipy.org#85]
We should have a page detailing how ChiPy is working with Python developers find a job and recruiters/companies who are looking for fill Python positions. @jerry-dumblauskas has the data and specific details of the process.

It would should be enough to have a contact email address where candidates can mail resumes or recruiters reach out to @jerry-dumblauskas.

**Comment by brianray** [comment]
something beyond this http://www.chipy.org/pages/referrals/ ?

**Comment by tathagata** [comment]
Other than the fact that it's not findable from our the landing page, that page is great for recruiting companies. However, for a developer looking for her/his next gig, how does she/he discover that ChiPy helps find Python jobs and what is the next step for getting that help?

How about adding two sections to the page

## Looking for an exciting Python position? ChiPy can help
- Send your resume to ... 
- Details about the process of how the resume will be used

## Successful Placements till now
- list of blurbs from developers who have been placed through ChiPy and how it was helpful

**Comment by brianray** [comment]
go for it, you have the power!! http://www.chipy.org/admin/flatpages/flatpage/5/

**Comment by tathagata** [comment]
Apparently I don't :( ...

**Comment by tathagata** [comment]
Updated http://www.chipy.org/admin/flatpages/flatpage/5/
