### ISSUE TITLE
Meetup.com sync missing records

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#86]
I just sync'd Feb Meetup and got only 12 additional RSVPs.  The Meetup.com site says 45

**Comment by emperorcezar** [comment]
Strange. I'll look into it.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by emperorcezar** [comment]
All fixed.
