### ISSUE TITLE
add "chicago-organizers@python.org" to contact form and confirmation

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#89]
Please add the email to the TO.

Also I don't see a confirmation that the contract form worked.

REF http://www.chipy.org/contact/

**Comment by tathagata** [comment]
From the README, it looks like this is an environment variable which needs to be reset on the server.
`export ENVELOPE_EMAIL_RECIPIENTS=admin@example.com`

**Comment by elmq0022** [comment]
This was updated on April 28th deploy.
