### ISSUE TITLE
show youtube/vimeo videos on website

### ISSUE THREAD

**Issue by jcalahor** [chicagopython/chipy.org#91]
topic section allows to enter video details from third party websites, however they are not showed when the topic is displayed. There needs to be possible to watch videos diectly in chipy.org website

**Comment by codersquid** [comment]
Hi, @pyvideo maintainer here. This issue title is a misnomer. We don't host videos, we index them and embed them on our site. If you want to embed videos on your site, use the embed mechanism from wherever they are hosted. e.g. for youtube, take a look at their docs to learn how to embed youtube videos [by hand](https://support.google.com/youtube/answer/171780?hl=en) or by [api](https://developers.google.com/youtube/iframe_api_reference).

That said, let me go off topic.

pyvideo has an [api](http://richard.readthedocs.org/en/latest/admin/api.html). example calls:

* category: http://pyvideo.org/api/v2/category/chipy
* video: http://pyvideo.org/api/v2/video/352

**Comment by emperorcezar** [comment]
I don't see a reason we couldn't link to the videos from the site. Is that
what you're talking about?

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by jcalahor** [comment]
title has been updated, what Brian wants is the ability to either go from the chipy website to the video where is hosted youtube (or whatever is hosted) or to embed the video and show on a the chipy website

**Comment by brianray** [comment]
Yes, just want to enable a way to associate an external video with a meeting so users can view on the chipy.org site. Don't need to host the actual video.

**Comment by codersquid** [comment]
That's what I thought from reading the original title, whence posting a clarification about not being able to embed pyvideo.org things. I think it would be cool if the site links to the category for chipy, and if anyone has questions about the richard api, you could ask us #richard on freenode or talk/email/etc. chipy could even run their own instance if it is helpful.

**Comment by JoeJasinski** [comment]
option: https://django-embed-video.readthedocs.io/en/v1.2.0/index.html

**Comment by elmq0022** [comment]
Added link to your tube channel.  Feel free to reopen if we still want embedded videos and how to approach.  Thanks.
