### ISSUE TITLE
Google OpenID 2.0 Auth is being deprecated

### ISSUE THREAD

**Issue by jramnani** [chicagopython/chipy.org#93]
Hello,

I tried to log into the Chipy web site today using Google as my OpenID provider, and was greeted by a message saying that web sites using Google as an OpenID 2.0 provider should switch to Google's OpenID Connect.

https://support.google.com/accounts/answer/6135882

**Comment by emperorcezar** [comment]
Thanks. We need to upgrade, I might have some time today, not sure though. Could be a bit till I get to it.

**Comment by emperorcezar** [comment]
All fixed now.

**Comment by brianray** [comment]
will you want to close this ticket then?
