### ISSUE TITLE
Topic Presenter's Name is blank

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#94]
For example http://www.chipy.org/admin/meetings/topic/120/ is blank.

**Comment by brianray** [comment]
Could this be an artifact of a blank name in the User table? http://www.chipy.org/admin/auth/user/?o=3.1

**Comment by emperorcezar** [comment]
That is very likely the cause.

**Comment by brianray** [comment]
bump

**Comment by JoeJasinski** [comment]
This appears to be a duplicate of this issue https://github.com/chicagopython/chipy.org/issues/137, and PR https://github.com/chicagopython/chipy.org/pull/153 resolves this.

**Comment by JoeJasinski** [comment]
closing per pr
