### ISSUE TITLE
Meetup.com sync sanity check reduced counts?

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#95]
I had 9 rsvps on Chipy.org
I checked meetup.com and it showed 39 before 
i hit sync, and the rsvps count changed to 38 on chipy.org

Something must be wrong with the sync.

**Comment by emperorcezar** [comment]
I'll take a look.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.
