### ISSUE TITLE
Update site to Python3

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#96]
We talked about this at ChiPy Organizer meeting

@JoeJasinski

**Comment by JoeJasinski** [comment]
I did a preliminary research on this a month ago or so.  These are the blockers:

 - django-forms-bootstrap
 - django-ical
 - django-pgsql-interval-field
 - django-storages
 - python-openid 


https://caniusepython3.com/check/553d2420-f258-4a84-b5cc-99b576cf25d5

**Comment by brianray** [comment]
that's a cool tool. little surprised about openid/python-openid but did see this https://github.com/openid/python-openid/pull/52 

The other ones look like a piece a cake.

**Comment by JoeJasinski** [comment]
Perhaps this can replace django-storages for python 3 support:

https://pypi.python.org/pypi/django-storages-redux

**Comment by JoeJasinski** [comment]
Python-openid has some activity in that issue, but there hasn't been a commit since 2014.  We might be able to use this in place of python-openid:

https://github.com/necaris/python3-openid

**Comment by emperorcezar** [comment]
I'm wondering if it would be worth us starting an initiative to port these requirements to Python 3?

**Comment by JoeJasinski** [comment]
Looks like there is some exiting work towards getting python-ical working

https://bitbucket.org/IanLewis/django-ical/pull-requests/6/updated-code-and-tests-to-support-python-3/diff

**Comment by JoeJasinski** [comment]
I actually think we are pretty close to Python 3 support.  I have a branch that's in progress related to this: https://github.com/JoeJasinski/chipy.org/tree/feature/django1.11

I built some (very very basic) unit tests to help ensure that the views involved in the site don't return 500 errors. All 16 pass before and after the update. All of the 3rd party modules have been update to versions that support python 3. The site runs pretty well inside of a Python 3 based Docker image.

The one tricky bit is that this branch moves from Django Social Auth to Python Social Auth.  While I think I've made all of the configuration changes needed, it's hard to test this without configuring all of the social auth accounts for the dev site, so still working that out.  Let me know if you have ideas about how to do this.

**Comment by JoeJasinski** [comment]
In pr https://github.com/chicagopython/chipy.org/pull/170, I merged in a lot of the python3 updates from the above branch (https://github.com/JoeJasinski/chipy.org/tree/feature/django1.11) and brought over the basic tests from that branch as well.

Before merging in the rest of the python3 branch, I need to figure out how to get a proper test environment to test the Python Social Auth changes.

**Comment by elmq0022** [comment]
Chipy.org official deployed on Python 3.6.9 Monday December 2nd.
