### ISSUE TITLE
accuracy on RSVP

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#97]
We should be sure to honor +1 from meetup.com.

**Comment by emperorcezar** [comment]
You'll have to add more details than this.

**Comment by brianray** [comment]
The problem is if we send our rsvp count to a venue, it does not account for +1's

**Comment by emperorcezar** [comment]
Ah, the plus 1's I read this wrong. Thanks!

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.
