### ISSUE TITLE
Logos on Site

### ISSUE THREAD

**Issue by brianray** [chicagopython/chipy.org#98]
@JoeJasinski  has more details and thoughts on this.

Things like:

* logo on website 

@agfor to add missing ones and to give feedback on how/when/where to show.

**Comment by agfor** [comment]
We should figure out how to get these on the home page this month:

![telnyx logo](https://cloud.githubusercontent.com/assets/963973/9209683/7575f6fa-403d-11e5-9abc-b71b3fc9445f.png)
![braintree](https://cloud.githubusercontent.com/assets/963973/9209689/7bcaee98-403d-11e5-8d70-bb2c59247085.png)

**Comment by emperorcezar** [comment]
Update the template with where you'd like them to be and pull request. :) I
"might" be able to do it tonight, we'll see. Pretty busy day.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by agfor** [comment]
Yeah I was figuring @JoeJasinski or I would PR it for you. Earliest I could take a look is next week.

**Comment by JoeJasinski** [comment]
My thoughts on this were just to make an admin interface for uploading logos and associating with a meeting so the current meetings and meeting history could list our sponsor links and logos.  

This will also require some planning is it requires that we be able to upload media to s3 or whatnot, which could incur additional changes to the Heroku account.  I'm glad to assist with this, but figure we should agree upon the feature-set first.  I probably won't have a chance to work on this until early next week.

**Comment by agfor** [comment]
@JoeJasinski these aren't logos for a specific meeting; they're the Platinum Sponsors.

**Comment by JoeJasinski** [comment]
I'm have some code in my local branch that does the following: 
  - adds a sponsor model and allows us to relate sponsors to a Meeting
       - I'm still integrating it into some of the templates
  - uses Amazon S3 to host media files (sponsor images) 
       - We of course will need s3 credentials 
       - A new environment variable called USE_S3 is available to toggle between locally hosted media files and s3-hosted media files. 
  - uses django-whitenoise (instead of dj-static) for hosting static content on Heroku (per Heroku's suggestion) 
  - updated a few requirements 

@emperorcezar I'd like to make some modifications to the css to accommodate the new sponsors.  What workflow do we use to compile the less content? 

Also, would it be possible to get a data-dump of the Heroku database?  I'd like to spin up a temporary development environment in my own heroku account to test out the new features with some actual data.

**Comment by emperorcezar** [comment]
@JoeJasinski I think since you have collaborator access on heroku you can just use the toolbelt to get a dump of the db. https://devcenter.heroku.com/articles/heroku-postgres-import-export Let me know if you don't have access and I'll make sure you get it.

In regards to the less, I was just compiling it locally and committing it.

**Comment by JoeJasinski** [comment]
Thanks @emperorcezar, 

I'm not sure if I have access; I have access to the chipy-voter app, but not sure about chipy.org.  (I don't see it in my dashboard, but I perhaps I have to visit a different location?)

**Comment by JoeJasinski** [comment]
At this point, I already have code in place for sponsor models.  I'll extend it to add the ability to post sponsors to the front page as well as to individual meetings.

**Comment by emperorcezar** [comment]
I added you.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by JoeJasinski** [comment]
Awesome - thank you!

**Comment by JoeJasinski** [comment]
@emperorcezar 

I think I have the basic functionality working for both meeting sponsors and general sponsors.  I tried to use as much of the bootstrap css tags for styling, but could use some UI tweaks (any advice here is appreciated). 

Current work is located here: 
https://github.com/JoeJasinski/chipy.org/tree/feature/sponsor

Features: 
  - Three new models added for MeetingSponsors and GeneralSponsors
  - Reversed the sort order in /meetings/past/ to show newest first
  - new urls:
      - /sponsors/detail/(slug)
          - large image and description
      - /sponsors/list/
          - list of all chipy sponsors
  - Added meeting sponsors logos/links to homepage
  - Added general sponsor section to homepage
  - Added sponsor links to /meetings/past/
  - Added sponsor, organizer, code of conduct links to the footer 
  - Plus the stuff mentioned above
 
Let me know what you think.

**Comment by emperorcezar** [comment]
@JoeJasinski Awesome! Sorry I've been camping this weekend and just catching up now. Let me know if you need anything else from me. I'm working on a laptop for a new employee and onboarding, so I can probably help later in the week.

**Comment by JoeJasinski** [comment]
Thank you for your help @emperorcezar.  Maybe when it's ready to merge, you could have a look at the changes to see if you have any questions?  I made a few changes to the media and static file settings (that should help hosting locally and on s3) that I want to make sure look good to you.  And we'll of course coordinate during deployment too.

**Comment by brianray** [comment]
So happy to see this moving forward. The sponsors will be happy too!

**Comment by emperorcezar** [comment]
@JoeJasinski Sounds Good. Let me know when and I'll jump on it. Deployment should be pretty smooth.

**Comment by JoeJasinski** [comment]
I've added a pull request here. 

https://github.com/chicagopython/chipy.org/pull/101

**Comment by brianray** [comment]
hi. bump

**Comment by JoeJasinski** [comment]
This was merged into master. Cezar is looking for a good time to deploy.

**Comment by JoeJasinski** [comment]
Ah, cool.  Looks like it was deployed. Thanks @emperorcezar !

**Comment by emperorcezar** [comment]
Sorry. I announced deployment in the IRC channel. A work habit.

----------------------------------------------------------------------------------
Father, dabbling at being a Python developer specializing in Django,
Cyclist, and home brewer.

**Comment by JoeJasinski** [comment]
I've added some UI updates based on some feedback.

**Comment by brianray** [comment]
looks done?

**Comment by JoeJasinski** [comment]
I think we can close this issue.
